version: '3.8'
name: "amazon-security-lake"
services:

  events-generator:
    image: wazuh/indexer-events-generator
    build:
      context: ../tools/events-generator
    container_name: events-generator
    depends_on:
      - wazuh.indexer
    networks:
      - net
    # TODO add healthcheck to indexer's service to avoid sending requests before API is ready.
    command: bash -c "sleep 10 && echo 'Ey, wake up!' && python run.py -a wazuh.indexer"

  wazuh.indexer:
    image: opensearchproject/opensearch:2.11.1
    container_name: wazuh.indexer
    depends_on:
      - wazuh-certs-generator
    hostname: wazuh.indexer
    environment:
      # - cluster.name=opensearch-cluster
      - node.name=wazuh.indexer
      - discovery.type=single-node
      # - cluster.initial_cluster_manager_nodes=opensearch-node
      - bootstrap.memory_lock=true
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - plugins.security.ssl.http.pemcert_filepath=/run/secrets/wazuh.indexer_http.pemcert
      - plugins.security.ssl.transport.pemcert_filepath=/run/secrets/wazuh.indexer_transport.pemcert
      - plugins.security.ssl.http.pemkey_filepath=/run/secrets/wazuh.indexer_http.pemkey
      - plugins.security.ssl.transport.pemkey_filepath=/run/secrets/wazuh.indexer_transport.pemkey
      - plugins.security.ssl.http.pemtrustedcas_filepath=/run/secrets/wazuh.indexer_http.pemtrustedcas
      - plugins.security.ssl.transport.pemtrustedcas_filepath=/run/secrets/wazuh.indexer_transport.pemtrustedcas
      - plugins.security.authcz.admin_dn="CN=wazuh.indexer,OU=Wazuh,O=Wazuh,L=California, C=US"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/opensearch/data
    networks:
      - net
    secrets:
      - wazuh.indexer_http.pemcert
      - wazuh.indexer_transport.pemcert
      - wazuh.indexer_http.pemkey
      - wazuh.indexer_transport.pemkey
      - wazuh.indexer_http.pemtrustedcas
      - wazuh.indexer_transport.pemtrustedcas
    #command: tail -f /dev/null

  wazuh.dashboard:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: wazuh.dashboard
    depends_on:
      - wazuh.indexer
    hostname: wazuh.dashboard
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://wazuh.indexer:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - net


  wazuh.integration.security.lake:
    image: wazuh/indexer-security-lake-integration
    build:
      context: ../amazon-security-lake
    container_name: wazuh.integration.security.lake
    depends_on:
      - wazuh.indexer
    hostname: wazuh.integration.security.lake
    environment:
      LOG_LEVEL: trace
      LOGSTASH_KEYSTORE_PASS: "SecretPassword"
      MONITORING_ENABLED: false
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ../amazon-security-lake/logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - net
    command: tail -f /dev/null
    # command: /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline/indexer-to-integrator.conf --path.settings /etc/logstash

  wazuh-certs-generator:
    image: wazuh-certs-generator
    build:
      dockerfile_inline: |
        FROM ubuntu:20.04
        RUN apt-get update && apt-get install openssl curl -y
        WORKDIR /
        COPY wazuh-certs-generator/entrypoint.sh /
        RUN chmod 700 /entrypoint.sh
        ENTRYPOINT ["/entrypoint.sh"]
    volumes:
      - ./certs/:/certificates/
      - ./wazuh-certs-generator/certs.yml:/config/certs.yml

volumes:
  data:

networks:
  net:

secrets:
  wazuh.indexer_http.pemcert:
    file: ./certs/wazuh.indexer.pem
  wazuh.indexer_transport.pemcert:
    file: ./certs/wazuh.indexer.pem
  wazuh.indexer_http.pemkey:
    file: ./certs/wazuh.indexer-key.pem
  wazuh.indexer_transport.pemkey:
    file: ./certs/wazuh.indexer-key.pem
  wazuh.indexer_http.pemtrustedcas:
    file: ./certs/root-ca.pem
  wazuh.indexer_transport.pemtrustedcas:
    file: ./certs/root-ca.pem
